CREATE TABLE IF NOT EXISTS USERS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USERID VARCHAR(350) NOT NULL,
    USERNAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    AVATAR VARCHAR(350) NOT NULL,
    REC_TOKEN VARCHAR(350),
    STAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS STORE(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(350) NOT NULL,
    EMAIL VARCHAR(350) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    STORE_ID INT NOT NULL,
    TITLE VARCHAR(350) NOT NULL,
    EMAIL VARCHAR(350) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    STAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CUSTOMERS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    STORE_ID INT NOT NULL,
    TITLE VARCHAR(350) NOT NULL,
    USERNAME  VARCHAR(350) NOT NULL,
    EMAIL VARCHAR(350) NOT NULL,
    PRICE VARCHAR(50) NOT NULL,
    CURRENCY VARCHAR(20) NOT NULL,
    ACTIVE VARCHAR(20) NOT NULL,
    STAMP TIMESTAMP,
    MONTH VARCHAR(60) NOT NULL,
    YEAR VARCHAR(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS ACTIVATOR(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CONTACT VARCHAR(350) NOT NULL,
    GAME_MAIL VARCHAR(3500) NOT NULL,
    HASH VARCHAR(350) NOT NULL,
    FIRST_DAY INT NOT NULL,
    FIRST_LIMIT INT NOT NULL,
    LOCK_TIME INT NOT NULL,
    DATE TIMESTAMP
);
CREATE TABLE IF NOT EXISTS SETTINGS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TITLE VARCHAR(250) NOT NULL,
    INSTALLED INT NOT NULL,
    DATE TIMESTAMP
);